[project]
name = "fincore-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
   "alembic>=1.18.5",
   "dotenv>=0.9.9",
   "fastapi[standard]>=0.141.1",
   "psycopg2-binary>=2.9.12",
   "psycopg[binary]>=3.3.4",
   "pydantic>=2.13.4",
   "pymysql>=1.2.0",
   "sqlalchemy>=2.0.51",
   "sqlmodel>=0.0.39",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
